services:
  db:
    image: postgres:15-alpine
    container_name: funding_cf_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: funding_cf
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
