ALTER TYPE "CompanyRole" ADD VALUE IF NOT EXISTS 'ADMIN';
ALTER TYPE "CompanyRole" ADD VALUE IF NOT EXISTS 'STAFF';
ALTER TYPE "CompanyRole" ADD VALUE IF NOT EXISTS 'REVIEWER';
ALTER TYPE "CompanyRole" ADD VALUE IF NOT EXISTS 'VIEWER';
