import type { CfRuleLike } from '@/lib/cf/types';

export const DEFAULT_CF_RULES: CfRuleLike[] = [
  {
    priority: 10,
    matchType: 'description_regex',
    matchValue: '(公庫|政策金融|日本政策|返済)',
    cfCategory: '借入返済',
    cfGroup: '財務支出',
    isPersonal: false,
  },
  {
    priority: 20,
    matchType: 'account',
    matchValue: '売上高',
    cfCategory: '売上入金',
    cfGroup: '変動費',
    isPersonal: false,
  },
  {
    priority: 20,
    matchType: 'account',
    matchValue: '売掛金',
    cfCategory: '売上入金',
    cfGroup: '変動費',
    isPersonal: false,
  },
  {
    priority: 20,
    matchType: 'account',
    matchValue: '雑収入',
    cfCategory: '雑収入',
    cfGroup: '変動費',
    isPersonal: false,
  },
  {
    priority: 20,
    matchType: 'account',
    matchValue: '長期借入金',
    cfCategory: '借入入金/返済',
    cfGroup: '財務支出',
    isPersonal: false,
  },
  {
    priority: 20,
    matchType: 'account',
    matchValue: '短期借入金',
    cfCategory: '借入入金/返済',
    cfGroup: '財務支出',
    isPersonal: false,
  },
  {
    priority: 20,
    matchType: 'account',
    matchValue: '役員借入金',
    cfCategory: '役員借入/個人資金投入',
    cfGroup: '財務支出',
    isPersonal: false,
  },
  {
    priority: 30,
    matchType: 'account',
    matchValue: '給料手当',
    cfCategory: '人件費',
    cfGroup: '人件費',
    isPersonal: false,
  },
  {
    priority: 30,
    matchType: 'account',
    matchValue: '法定福利費',
    cfCategory: '人件費',
    cfGroup: '人件費',
    isPersonal: false,
  },
  {
    priority: 30,
    matchType: 'account',
    matchValue: '地代家賃',
    cfCategory: '地代家賃',
    cfGroup: '固定費',
    isPersonal: false,
  },
  {
    priority: 30,
    matchType: 'account',
    matchValue: '水道光熱費',
    cfCategory: '水道光熱費',
    cfGroup: '固定費',
    isPersonal: false,
  },
  {
    priority: 30,
    matchType: 'account',
    matchValue: '通信費',
    cfCategory: '通信費',
    cfGroup: '固定費',
    isPersonal: false,
  },
  {
    priority: 30,
    matchType: 'account',
    matchValue: '広告宣伝費',
    cfCategory: '広告宣伝費',
    cfGroup: '変動費',
    isPersonal: false,
  },
  {
    priority: 30,
    matchType: 'account',
    matchValue: '消耗品費',
    cfCategory: '消耗品費',
    cfGroup: '変動費',
    isPersonal: false,
  },
  {
    priority: 30,
    matchType: 'account',
    matchValue: '外注費',
    cfCategory: '外注費',
    cfGroup: '変動費',
    isPersonal: false,
  },
  {
    priority: 30,
    matchType: 'account',
    matchValue: '法人税等',
    cfCategory: '税金支払',
    cfGroup: '税金',
    isPersonal: false,
  },
  {
    priority: 30,
    matchType: 'account',
    matchValue: '租税公課',
    cfCategory: '税金支払',
    cfGroup: '税金',
    isPersonal: false,
  },
  {
    priority: 40,
    matchType: 'account',
    matchValue: '事業主貸',
    cfCategory: '個人支出',
    cfGroup: '個人関連',
    isPersonal: true,
  },
  {
    priority: 40,
    matchType: 'account',
    matchValue: '事業主借',
    cfCategory: '個人資金投入',
    cfGroup: '個人関連',
    isPersonal: true,
  },
  {
    priority: 40,
    matchType: 'account',
    matchValue: '役員貸付金',
    cfCategory: '個人支出',
    cfGroup: '個人関連',
    isPersonal: true,
  },
];

export function isCashAccountName(name: string | null | undefined): boolean {
  if (!name) return false;
  return ['現金', '普通預金', '当座預金', '定期預金', '預金'].some((keyword) =>
    name.includes(keyword),
  );
}
